# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Education
    url: education/
    weight: 10
  - name: Experience
    url: content/experience.md
    weight: 20
  - name: Skills
    url: content/skills.md
    weight: 30
  - name: Publications
    url: publication/
    weight: 40
  - name: Projects
    url: projects/
    weight: 50
  - name: Certificates
    url: certificates/
    weight: 60
  - name: Blog
    url: blog/
    weight: 70
  - name: Contact
    url: content/contact.md
    weight: 80
