# Navigation Links
main:
  - name: About
    url: /about/
    weight: 1
  - name: Research
    url: /research/
    weight: 2
  - name: Publications
    url: /publications/
    weight: 3
  - name: Hobbies
    url: /hobbies/
    weight: 4
  - name: Photography
    url: /photography/
    weight: 5
  - name: Blog
    url: /blog/
    weight: 6
  - name: Teaching
    url: /teaching/
    weight: 7
  - name: CV / Contact
    url: /cv/
    weight: 8

